# Generated by Django 5.2 on 2025-05-31 09:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='advertiseme_status_3ed8c6_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='advertiseme_categor_3c4e6e_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft - Pending Review'), ('active', 'Active - Available for Rent'), ('rented', 'Rented - Currently Rented'), ('maintenance', 'Under Maintenance - Needs Action'), ('suspended', 'Suspended - Listing Disabled')], default='draft', help_text='Product status', max_length=255),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'created_at'], name='advertiseme_status_5168a1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='advertiseme_categor_314ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['location'], name='advertiseme_locatio_23427e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['average_rating'], name='advertiseme_average_c27816_idx'),
        ),
    ]
