# Generated by Django 5.2 on 2025-05-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_remove_product_advertiseme_status_3ed8c6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_year',
            field=models.CharField(help_text='Year product was purchased (YYYY)', max_length=4),
        ),
    ]
